version: "3"
services:
  nodeserver:
    restart: always
    build:
      context: ./app
    ports:
      - "82:3003"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "87:82"
